### ISSUE TITLE
Page Ids to strings?

### ISSUE THREAD

**Issue by NMerz** [pandeyshubham25/pagerank#5]
Data cleaning would be easier switching page ids to strings. Any thoughts on if we want to the performance penalty of doing so?

Not a huge issue to map them if needed.

**Comment by pandeyshubham25** [comment]
Data cleaning will be done offline, so wouldn't affect our performance metrics, so we can try sticking to integers. Lets map them to int and save that instead?

**Comment by NMerz** [comment]
Alright, will do

**Comment by NMerz** [comment]
Resolved by #3
